repos:
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
          - id: isort
    - repo: https://github.com/ambv/black
      rev: 19.3b0
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-byte-order-marker
          - id: trailing-whitespace
          - id: mixed-line-ending
            args: ["--fix=lf"]
          - id: check-merge-conflict
          - id: check-json
          - id: check-yaml
          - id: detect-aws-credentials
          - id: detect-private-key
          - id: pretty-format-json
            args: ["--autofix", "--no-sort-keys", "--indent=4"]
    - repo: https://github.com/prettier/prettier
      rev: 1.18.2
      hooks:
          - id: prettier
            files: \.(css|less|scss|ts|tsx|graphql|gql|json|js|jsx|md)$
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.8
      hooks:
          - id: flake8
