exclude: ".*/vendor/.*"
repos:
    - repo: https://github.com/PyCQA/isort
      rev: 5.13.2
      hooks:
          - id: isort
    - repo: https://github.com/psf/black
      rev: 24.3.0
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-added-large-files
            args: ["--maxkb=128"]
          - id: check-ast
          - id: check-byte-order-marker
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-xml
          - id: check-yaml
          - id: debug-statements
          - id: detect-aws-credentials
            args: ["--allow-missing-credentials"]
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: ["--fix=lf"]
          - id: pretty-format-json
            args: ["--autofix", "--no-sort-keys", "--indent=4"]
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v4.0.0-alpha.8
      hooks:
          - id: prettier
            files: \.(css|less|scss|ts|tsx|graphql|gql|json|js|jsx|md)$
    - repo: https://github.com/PyCQA/flake8
      rev: 7.0.0
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-assertive
                - flake8-builtins
                - flake8-comprehensions
                - flake8-eradicate
                - flake8-logging-format
