name: CI

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t docker.pkg.github.com/acdha/microdata-extractor/microdata-extractor:latest .
    - name: Publish the Docker image
      run: |
        docker login docker.pkg.github.com -u acdha -p ${GITHUB_TOKEN}
        docker push docker.pkg.github.com/acdha/microdata-extractor/microdata-extractor:latest
