name: CI

on:
    push:
        branches:
            - master

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run pre-commit
              run: |
                  docker pull docker.pkg.github.com/acdha/pre-commit-docker/pre-commit-docker:master
                  docker run --volume "$PWD":/code docker.pkg.github.com/acdha/pre-commit-docker/pre-commit-docker:master

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Build the Docker image
              run: docker build -t docker.pkg.github.com/${GITHUB_REPOSITORY}/$(basename "${GITHUB_REPOSITORY}"):master .
            - name: Publish the Docker image
              env:
                  PACKAGE_PUBLICATION_TOKEN: ${{ secrets.PACKAGE_PUBLICATION_TOKEN }}
              run: |
                  docker login docker.pkg.github.com -u acdha -p ${PACKAGE_PUBLICATION_TOKEN}
                  docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/$(basename "${GITHUB_REPOSITORY}"):master
